/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PharmaRouteImport } from './routes/pharma'
import { Route as MetodologieRouteImport } from './routes/metodologie'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as DateLiveRouteImport } from './routes/date-live'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const PharmaRoute = PharmaRouteImport.update({
  id: '/pharma',
  path: '/pharma',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologieRoute = MetodologieRouteImport.update({
  id: '/metodologie',
  path: '/metodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const DateLiveRoute = DateLiveRouteImport.update({
  id: '/date-live',
  path: '/date-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/date-live': typeof DateLiveRoute
  '/despre': typeof DespreRoute
  '/metodologie': typeof MetodologieRoute
  '/pharma': typeof PharmaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/date-live': typeof DateLiveRoute
  '/despre': typeof DespreRoute
  '/metodologie': typeof MetodologieRoute
  '/pharma': typeof PharmaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/date-live': typeof DateLiveRoute
  '/despre': typeof DespreRoute
  '/metodologie': typeof MetodologieRoute
  '/pharma': typeof PharmaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/date-live'
    | '/despre'
    | '/metodologie'
    | '/pharma'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/date-live' | '/despre' | '/metodologie' | '/pharma'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/date-live'
    | '/despre'
    | '/metodologie'
    | '/pharma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DateLiveRoute: typeof DateLiveRoute
  DespreRoute: typeof DespreRoute
  MetodologieRoute: typeof MetodologieRoute
  PharmaRoute: typeof PharmaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pharma': {
      id: '/pharma'
      path: '/pharma'
      fullPath: '/pharma'
      preLoaderRoute: typeof PharmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologie': {
      id: '/metodologie'
      path: '/metodologie'
      fullPath: '/metodologie'
      preLoaderRoute: typeof MetodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-live': {
      id: '/date-live'
      path: '/date-live'
      fullPath: '/date-live'
      preLoaderRoute: typeof DateLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DateLiveRoute: DateLiveRoute,
  DespreRoute: DespreRoute,
  MetodologieRoute: MetodologieRoute,
  PharmaRoute: PharmaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
