/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpacRouteImport } from './routes/spac'
import { Route as PrognozaRouteImport } from './routes/prognoza'
import { Route as PharmaRouteImport } from './routes/pharma'
import { Route as MicrobiomeRouteImport } from './routes/microbiome'
import { Route as MetodologieRouteImport } from './routes/metodologie'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmaIndexRouteImport } from './routes/pharma.index'
import { Route as PharmaDocumentatieRouteImport } from './routes/pharma.documentatie'

const SpacRoute = SpacRouteImport.update({
  id: '/spac',
  path: '/spac',
  getParentRoute: () => rootRouteImport,
} as any)
const PrognozaRoute = PrognozaRouteImport.update({
  id: '/prognoza',
  path: '/prognoza',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaRoute = PharmaRouteImport.update({
  id: '/pharma',
  path: '/pharma',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrobiomeRoute = MicrobiomeRouteImport.update({
  id: '/microbiome',
  path: '/microbiome',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologieRoute = MetodologieRouteImport.update({
  id: '/metodologie',
  path: '/metodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaIndexRoute = PharmaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmaRoute,
} as any)
const PharmaDocumentatieRoute = PharmaDocumentatieRouteImport.update({
  id: '/documentatie',
  path: '/documentatie',
  getParentRoute: () => PharmaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/metodologie': typeof MetodologieRoute
  '/microbiome': typeof MicrobiomeRoute
  '/pharma': typeof PharmaRouteWithChildren
  '/prognoza': typeof PrognozaRoute
  '/spac': typeof SpacRoute
  '/pharma/documentatie': typeof PharmaDocumentatieRoute
  '/pharma/': typeof PharmaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/metodologie': typeof MetodologieRoute
  '/microbiome': typeof MicrobiomeRoute
  '/prognoza': typeof PrognozaRoute
  '/spac': typeof SpacRoute
  '/pharma/documentatie': typeof PharmaDocumentatieRoute
  '/pharma': typeof PharmaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/metodologie': typeof MetodologieRoute
  '/microbiome': typeof MicrobiomeRoute
  '/pharma': typeof PharmaRouteWithChildren
  '/prognoza': typeof PrognozaRoute
  '/spac': typeof SpacRoute
  '/pharma/documentatie': typeof PharmaDocumentatieRoute
  '/pharma/': typeof PharmaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/despre'
    | '/metodologie'
    | '/microbiome'
    | '/pharma'
    | '/prognoza'
    | '/spac'
    | '/pharma/documentatie'
    | '/pharma/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/despre'
    | '/metodologie'
    | '/microbiome'
    | '/prognoza'
    | '/spac'
    | '/pharma/documentatie'
    | '/pharma'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/despre'
    | '/metodologie'
    | '/microbiome'
    | '/pharma'
    | '/prognoza'
    | '/spac'
    | '/pharma/documentatie'
    | '/pharma/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  MetodologieRoute: typeof MetodologieRoute
  MicrobiomeRoute: typeof MicrobiomeRoute
  PharmaRoute: typeof PharmaRouteWithChildren
  PrognozaRoute: typeof PrognozaRoute
  SpacRoute: typeof SpacRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spac': {
      id: '/spac'
      path: '/spac'
      fullPath: '/spac'
      preLoaderRoute: typeof SpacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prognoza': {
      id: '/prognoza'
      path: '/prognoza'
      fullPath: '/prognoza'
      preLoaderRoute: typeof PrognozaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharma': {
      id: '/pharma'
      path: '/pharma'
      fullPath: '/pharma'
      preLoaderRoute: typeof PharmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microbiome': {
      id: '/microbiome'
      path: '/microbiome'
      fullPath: '/microbiome'
      preLoaderRoute: typeof MicrobiomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologie': {
      id: '/metodologie'
      path: '/metodologie'
      fullPath: '/metodologie'
      preLoaderRoute: typeof MetodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharma/': {
      id: '/pharma/'
      path: '/'
      fullPath: '/pharma/'
      preLoaderRoute: typeof PharmaIndexRouteImport
      parentRoute: typeof PharmaRoute
    }
    '/pharma/documentatie': {
      id: '/pharma/documentatie'
      path: '/documentatie'
      fullPath: '/pharma/documentatie'
      preLoaderRoute: typeof PharmaDocumentatieRouteImport
      parentRoute: typeof PharmaRoute
    }
  }
}

interface PharmaRouteChildren {
  PharmaDocumentatieRoute: typeof PharmaDocumentatieRoute
  PharmaIndexRoute: typeof PharmaIndexRoute
}

const PharmaRouteChildren: PharmaRouteChildren = {
  PharmaDocumentatieRoute: PharmaDocumentatieRoute,
  PharmaIndexRoute: PharmaIndexRoute,
}

const PharmaRouteWithChildren =
  PharmaRoute._addFileChildren(PharmaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  MetodologieRoute: MetodologieRoute,
  MicrobiomeRoute: MicrobiomeRoute,
  PharmaRoute: PharmaRouteWithChildren,
  PrognozaRoute: PrognozaRoute,
  SpacRoute: SpacRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
